from pptx import Presentation
from pptx.util import Pt
from pptx.dml.color import RGBColor
import ollama


def ask_llm(prompt):

    response = ollama.chat(
        model="llama3",
        messages=[{"role": "user", "content": prompt}]
    )

    return response["message"]["content"]


def generate_ppt(text):

    prompt = f"""
You are an academic presentation creator.

Convert the research paper into a professional research presentation.

Format strictly like this:

Title: <title>

Introduction
- bullet
- bullet
- bullet

Problem Statement
- bullet
- bullet

Methodology
- bullet
- bullet
- bullet

Results
- bullet
- bullet

Conclusion
- bullet
- bullet

Keep bullet points short (max 10 words).
Maximum 5 bullets per slide.

Paper:
{text[:4000]}
"""

    slides_text = ask_llm(prompt)

    prs = Presentation()

    # ---------- TITLE SLIDE ----------
    title_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_layout)

    slide.shapes.title.text = "Research Paper Analysis"

    subtitle = slide.placeholders[1]
    subtitle.text = "Generated by InsightPaper Pro"

    # Style title
    for paragraph in slide.shapes.title.text_frame.paragraphs:
        for run in paragraph.runs:
            run.font.size = Pt(40)

    # ---------- PARSE SECTIONS ----------
    sections = slides_text.split("\n\n")

    for section in sections:

        lines = section.split("\n")

        if len(lines) < 2:
            continue

        title = lines[0]

        bullets = lines[1:]

        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)

        slide.shapes.title.text = title

        body = slide.shapes.placeholders[1].text_frame

        body.clear()

        for bullet in bullets[:5]:

            text = bullet.replace("-", "").strip()

            p = body.add_paragraph()
            p.text = text
            p.level = 0

            p.font.size = Pt(22)

            p.font.color.rgb = RGBColor(0, 0, 0)

    prs.save("research_presentation.pptx")

    return "research_presentation.pptx"